### ISSUE TITLE
XGS+Imgui1.8

### ISSUE THREAD

**Issue by webspacecreations** [jmthompson/xgs#2]
[xgs-imgui1_8.zip](https://github.com/jmthompson/xgs/files/5759839/xgs-imgui1_8.zip)

RenderDrawListsFn was deprecated back at ImGui 1.6. I played with updating this, but considering potential imminent changes related to rendering pipeline, decided to just re-activate RenderDrawListsFn in ImGui. In this respect, ImGui is now "non-standard," but it provides a gentler migration path. Changes made to Imgui.cpp & .h to re-enable support for this were minor.

XGS emulator code is mostly unchanged, with the following minor changes in GUI.cc
Line 260: Added ImGui::CreateContext();
Line 314: ImGui::Shutdown now requires an ImGuiContext argument. So, added ImGui::GetCurrentContext in order to pass context to Shutdown call

**Comment by jmthompson** [comment]
Merged into master.
